### ISSUE TITLE
Server crashes when shooting glass ocean portal with Hailstorm multishot

### ISSUE THREAD

**Issue by Aphyxia** [cleannrooster/Spellblade-Next#11]
Server crashes while a player shoots the glass ocean portal created by the hex invaders with a hailstorm bow that has the multishot skill. It doesn't crash when shooting it with a bow that has the other two skills.
[crash-2023-08-02_22.56.05-server.txt](https://github.com/cleannrooster/Spellblade-Next/files/12244189/crash-2023-08-02_22.56.05-server.txt)

**Comment by cleannrooster** [comment]
It's an issue with Respawnable Pets that seems to have been fixed for the 1.20.1 version of the mod, but not for 1.19.2. My advice is to remove Respawnable Pets. I can push an update at some point to fix this if i can.

EDIT: I have spoken with the developer of Prominence and they are fixing it for this modpack.

**Comment by Aphyxia** [comment]
Thanks. I have removed respawnable pets for the time being.
