### ISSUE TITLE
Primordial armor elemental novas triplicate Ad Astra rockets

### ISSUE THREAD

**Issue by Aphyxia** [cleannrooster/Spellblade-Next#12]
Primordial armor elemental novas triplicate rockets from the Ad Astra mod.
Video demonstration: https://www.youtube.com/watch?v=LuPBHBjbW1U
Spells also target the rocket but after their strike only one rocket is dropped.
Using the Prominence I latest modpack.

**Comment by cleannrooster** [comment]
Thank you! I've been meaning to make only one nova go out at a time rather than all 3 so this will likely fix the issue.
