### ISSUE TITLE
Nasty compat error with this and Gigeresque

### ISSUE THREAD

**Issue by Sunconure11** [cleannrooster/Spellblade-Next#13]
https://pastebin.com/6iy1FXUx

Had to trim this out of a massive log.

https://github.com/cybercat-mods/gigeresque/issues/176

Version of MC is 1.19.2.

**Comment by Sunconure11** [comment]
What happens is that a player ends up getting booted out of a world with an invalid player data error.

**Comment by cleannrooster** [comment]
Should be fixed in the newest version being uploaded right now
